#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

typedef enum {FALSE, TRUE} BOOL;
typedef enum {OK, ERR_FILE_NOT_FOUND, ERR_FILE_NOT_PERM, IMPOSSIBLE_VALID_BOARD, NOT_ENOUGH_MINERALS} CODE;

enum {EASY=1, MEDIUM=3, HARD=5} DIFFICULTY;

#endif